import { NextPage } from 'next'
import Head from 'next/head'
import React, { useState } from 'react'

const Calculator: NextPage = () => {
  const [instanceValue, setInstanceValue] = useState<number>(1)
  const onValueChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.currentTarget.value === "0")
      setInstanceValue(0)
    if (e.currentTarget.value === "1")
      setInstanceValue(1)
    else (e.currentTarget.value === "2")
    setInstanceValue(2)
  }
  return (
    <>
      <Head>
        <title>Грошев и партньори - Калкулатор</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='flex p-4'>
        <div className='max-w-2xl justify-center items-center m-auto'>
          <form action="" className='card-body shadow-2xl rounded form-control'>
            <div className='flex flex-col justify-between items-center'>
              <label className='text-center text-lg text-indigo-500 font-bold'>
                Интерес
              </label>
              <input type="number" placeholder="BGN" className="input input-bordered input-info w-full text-center max-w-xs  " />
            </div>
            <div className="p-2">
              <p className='text-center text-lg text-indigo-500 font-bold'>Извънпроцесуална дейност</p>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Съставяне на писмен договор по чл. 6, ал. 8, пр. 1 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Съставяне на нотариални актове за собственост, продажба, замяна, дарение, ипотека, суперфиция и сервитути по чл. 6, ал. 8, пр. 2 и сл. от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Съставяне на извънсъдебна спогодба по чл. 6, ал. 8 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
            </div>
            <div className="p-2">
              <p className='text-center text-lg text-indigo-500 font-bold'>Възнаграждения по граждански дела</p>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  за дела, заведени преди 04.11.2022
                </label>
                <input aria-label='are' type="radio" name="radio-10" required className="radio checked:radio-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  за дела, заведени след 04.11.2022
                </label>
                <input aria-label='are' type="radio" name="radio-10" required className="radio checked:radio-accent" />
                <span className='divider'></span>
              </div>
              <div className='divider'></div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Заповедно производство чл. 7, ал. 7 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Исково производство чл. 7, ал. 2 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='divider'></div>
              <div className='py-2'>
                <div className='flex justify-between items-center py-2'>
                  <label className='text-lg font-medium'>
                    Първа инстанция
                  </label>
                  <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
                </div>
                <div className='flex justify-between items-center py-2'>
                  <label className='text-lg font-medium'>
                    Втора инстанция
                  </label>
                  <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
                </div>
                <div className='flex justify-between items-centerflex py-2'>
                  <label className='text-lg font-medium'>
                    Трета инстанция
                  </label>
                  <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
                </div>
                <div className='divider'></div>
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Обезпечително производство чл. 7, ал. 7, пр. 1 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Производство по издаване на изпълнителен лист въз основа на арбитражни и чуждестранни съдебни актове чл. 7, ал. 7, пр. 2 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Изпълнително дело чл. 10, т. 2 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
            </div>
            <div className="p-2">
              <p className='text-center text-lg text-indigo-500 font-bold'>
                Възнаграждения по административни дела с определен материален интерес
              </p>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Производство пред административен съд – чл. 8, ал. 1 от Наредбата
                </label>
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Първа инстанция
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Касационна инстанция
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <div className='divider'></div>
              <div className='flex justify-center items-center'>
                <label className='label-text text-lg font-medium'>
                  Жалбоподател:
                </label>
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  ЮЛ с нестопанска цел или физическо лице, което не е търговец
                </label>
                <input aria-label='are' type="radio" name="radio-10" required className="radio checked:radio-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  ЮЛ Търговец или ЕТ
                </label>
                <input aria-label='are' type="radio" name="radio-10" required className="radio checked:radio-accent" />
                <span className='divider'></span>
              </div>
            </div>
          </form>
        </div>
      </div>
    </>
  )
}

export default Calculator