import { NextPage } from 'next'
import Head from 'next/head'
import { FormEvent, useMemo, useState } from 'react';

type FormValues = {
  interest: number;
  agreement1: boolean;
  agreement2: boolean;
  agreement3: boolean;
  compensation: string;
  commandProduction: boolean;
  claimProduction: boolean;
  firstInstance: boolean;
  secondInstance: boolean;
  thirdInstance: boolean;
  provisionalProceedings: boolean;
};

const Calculator: NextPage = () => {

  const initialValues: FormValues = {
    interest: 0,
    agreement1: false,
    agreement2: false,
    agreement3: false,
    compensation: "",
    commandProduction: false,
    claimProduction: false,
    firstInstance: false,
    secondInstance: false,
    thirdInstance: false,
    provisionalProceedings: false,
  };

  const [values, setValues] = useState<FormValues>(initialValues);

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    console.log("Form submitted with values: ", values);
  };

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const name = event.target.name;
    const value =
      event.target.type === "checkbox"
        ? event.target.checked
        : event.target.value;
    setValues({ ...values, [name]: value });
  };


  return (
    <>
      <Head>
        <title>Грошев и партньори - Калкулатор</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='flex p-4'>
        <div className='max-w-2xl justify-center items-center m-auto'>
          <form
            onSubmit={handleSubmit}
            className='card-body shadow-2xl rounded form-control'>
            <div className='flex flex-col justify-between items-center'>
              <label className='text-center text-lg text-indigo-500 font-bold'>
                Интерес
              </label>
              <input
                type="number"
                placeholder="BGN"
                name="interest"
                value={values.interest}
                onChange={handleChange}
                className="input input-bordered input-info w-full text-center max-w-xs  " />
            </div>
            <div className="p-2">
              <p className='text-center text-lg text-indigo-500 font-bold'>Извънпроцесуална дейност</p>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Съставяне на писмен договор по чл. 6, ал. 8, пр. 1 от Наредбата
                </label>
                <input
                  aria-label='are'
                  type="checkbox"
                  name="agreement1"
                  checked={values.agreement1}
                  onChange={handleChange}
                  className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Съставяне на нотариални актове за собственост, продажба, замяна, дарение, ипотека, суперфиция и сервитути по чл. 6, ал. 8, пр. 2 и сл. от Наредбата
                </label>
                <input
                  aria-label='are'
                  type="checkbox"
                  name="agreement2"
                  checked={values.agreement2}
                  onChange={handleChange}
                  className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Съставяне на извънсъдебна спогодба по чл. 6, ал. 8 от Наредбата
                </label>
                <input
                  aria-label='are'
                  type="checkbox"
                  name="agreement3"
                  checked={values.agreement3}
                  onChange={handleChange}
                  className="checkbox checkbox-accent" />
              </div>
              <br />
            </div>
            <div className="p-2">
              <p className='text-center text-lg text-indigo-500 font-bold'>Възнаграждения по граждански дела</p>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  за дела, заведени преди 04.11.2022
                </label>
                <input
                  aria-label='are'
                  type="radio"
                  name="commandProduction"
                  required
                  className="radio checked:radio-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  за дела, заведени след 04.11.2022
                </label>
                <input
                  aria-label='are'
                  type="radio"
                  name="commandProduction"
                  required
                  className="radio checked:radio-accent" />
                <span className='divider'></span>
              </div>
              <div className='divider'></div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Заповедно производство чл. 7, ал. 7 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Исково производство чл. 7, ал. 2 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='divider'></div>
              <div className='py-2'>
                <div className='flex justify-between items-center py-2'>
                  <label className='text-lg font-medium'>
                    Първа инстанция
                  </label>
                  <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
                </div>
                <div className='flex justify-between items-center py-2'>
                  <label className='text-lg font-medium'>
                    Втора инстанция
                  </label>
                  <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
                </div>
                <div className='flex justify-between items-centerflex py-2'>
                  <label className='text-lg font-medium'>
                    Трета инстанция
                  </label>
                  <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
                </div>
                <div className='divider'></div>
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Обезпечително производство чл. 7, ал. 7, пр. 1 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Производство по издаване на изпълнителен лист въз основа на арбитражни и чуждестранни съдебни актове чл. 7, ал. 7, пр. 2 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='text-lg font-medium'>
                  Изпълнително дело чл. 10, т. 2 от Наредбата
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
            </div>
            <div className="p-2">
              <p className='text-center text-lg text-indigo-500 font-bold'>
                Възнаграждения по административни дела с определен материален интерес
              </p>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Производство пред административен съд – чл. 8, ал. 1 от Наредбата
                </label>
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Първа инстанция
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className='label-text text-lg font-medium'>
                  Касационна инстанция
                </label>
                <input aria-label='are' type="checkbox" className="checkbox checkbox-accent" />
              </div>
              <div className='divider'></div>
              <div className='flex justify-center items-center'>
                <label className='label-text text-lg font-medium'>
                  Жалбоподател:
                </label>
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  ЮЛ с нестопанска цел или физическо лице, което не е търговец
                </label>
                <input aria-label='are' type="radio" name="radio-10" required className="radio checked:radio-accent" />
              </div>
              <br />
              <div className='flex justify-between items-center'>
                <label className="label-text text-lg font-medium w-full">
                  ЮЛ Търговец или ЕТ
                </label>
                <input aria-label='are' type="radio" name="radio-10" required className="radio checked:radio-accent" />
                <span className='divider'></span>
              </div>
            </div>
            <button type="submit" className='card items-center border-2 border-primary p-3'>Send</button>
            <div className="card border-2 border-primary p-3">{ }</div>
          </form>
        </div>
      </div>
    </>
  )
}

export default Calculator