import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const News: NextPage = () => {
  return (
    <>
      <Head>
        <title>Грошев и партньори Новини и Публикации</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>news</div>
    </>
  )
}

export default News