import { useNews } from '@/hooks/useNews'
import { NextPage } from 'next'
import Head from 'next/head'
import React, { Fragment, memo } from 'react'
import Loading from '../components/Loading'

const News: NextPage = () => {

  const { news, isLoading } = useNews()
  return (
    <>
      <Head>
        <title>Грошев и партньори Новини и Публикации</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''></link>
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet"></link>
      </Head>
      <div className='flex flex-col min-h-full w-full '>
        <div className='md:max-w-4xl max-w-sm z-0 p-4 h-full self-center'>
          <div>{isLoading ? <Loading /> :
            news?.map((post) => {
              return (
                <Fragment key={post.id}>
                  <div className="card card-bordered max-w-full shadow-xl mb-4">
                    <div className="card-body max-w-full">
                      <h2 className="card-title">{post.title}</h2>
                      <p
                        dangerouslySetInnerHTML={{ __html: post.content }}
                        className='w-[100%]'
                      ></p>
                    </div>
                  </div>
                </Fragment>
              )
            })}
          </div>
        </div>
      </div>
    </>
  )
}

export default memo(News)