import { NextPage } from 'next'
import Head from 'next/head'
import React, { memo } from 'react'
import Loading from './components/Loading'
import { useNews } from './hooks/useNews'

const News: NextPage = () => {

  const { news, isLoading } = useNews()
  console.log(news)
  return (
    <>
      <Head>
        <title>Грошев и партньори Новини и Публикации</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className='max-w-4xl p-4'>
        <div >{isLoading ? <Loading /> :
          news.map((post) => {
            return (
              <>
                <div key={post.id} className="card max-w-full bg-base-100 shadow-xl mb-4">
                  <div className="card-body max-w-fit">
                    <h2 className="card-title">{post.title}</h2>
                    <p dangerouslySetInnerHTML={{ __html: post.content }}></p>
                  </div>
                </div>
              </>
            )
          })}
        </div>
      </main>
    </>
  )
}

export default memo(News)